stages:
  - sync
  - build

sync_from_github:
  stage: sync
  image: alpine/git
  script:
    - git clone --branch main --single-branch https://github.com/Coderxrohan/reporeply-frontend.git source
    - cd source
    - echo "Pulled main branch from GitHub"
  rules:
    - when: manual

build:
  stage: build
  script:
    - echo "Build step here"
  rules:
    - when: manual
